# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
# scheb_two_factor:
#     security_tokens:
#         - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
#         - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
# scheb_two_factor:
#   security_tokens:
#     - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
#     - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
#     - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
#     - Acme\AuthenticationBundle\Token\CustomAuthenticationToken
#   google:
#     enabled: true