#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml

app_negociation_stats:
    path: /negociation/stats
    controller: App\Controller\NegociationController::statistics
    methods: ['GET']
